#!/usr/bin/env bash
#Check subdomain records

check_subdomain_record() {
  subdomain=$1
  domain=$2

  # Retrieve DNS records 
  dns_records=$(dig +short $subdomain.$domain)

  # Check  DNS records
  if [[ -z $dns_records ]]; then
    echo "No DNS record found for subdomain $subdomain"
  else
    # Loop DNS records
    for record in $dns_records; do
      # Record type
      if [[ $record =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        record_type="A"
      else
        record_type=$(dig +short -t $record $subdomain.$domain | awk '{print $4}')
      fi
      
      # Print
      echo "The subdomain $subdomain is a $record_type record and points to $record"
    done
  fi
}


domain=$1
subdomain=$2

if [[ -z $subdomain ]]; then
  check_subdomain_record www $domain
  check_subdomain_record lb-01 $domain
  check_subdomain_record web-01 $domain
  check_subdomain_record web-02 $domain
else
  check_subdomain_record $subdomain $domain
fi
